repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.1
  hooks:
    # Run the linter
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix]
    # Run isort.
    - id: ruff
      args: [ --select, I, --fix, --exit-non-zero-on-fix]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    # Run pytest
    - id: pytest
      name: pytest
      entry: pytest src/tests/
      language: python
      pass_filenames: false
      always_run: true
